name: Update heroicons

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      branch_name: update-heroicons
    steps:
      - uses: actions/checkout@v3

      - name: Get current heroicons version
        run: |
          pr_version=$(curl -Lfs https://raw.githubusercontent.com/tmcknight/Blazor.Heroicons/${{ env.branch_name }}/.heroicons-version) || true
          if [ -z "$pr_version"]
          then
            echo "current_version=$pr_version" >> $GITHUB_ENV
          else
            echo "current_version=$(<.heroicons-version)" >> $GITHUB_ENV
          fi

      - name: Get latest github release
        id: latest_release
        uses: oprypin/find-latest-tag@v1
        with:
          repository: tailwindlabs/heroicons
          releases-only: true

      - name: Setup python
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get latest release
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        run: python scripts/get-latest-heroicons.py

      - uses: tibdex/github-app-token@v1
        name: Get Tombot-9000 token
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        id: generate-token
        with:
          app_id: ${{ secrets.TOMBOT_APP_ID }}
          private_key: ${{ secrets.TOMBOT_PRIVATE_KEY }}

      - name: Create pull request
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ env.branch_name }}
          title: Update heroicons to latest version
          commit-message: Update heroicons to ${{ steps.latest_release.outputs.tag }}
          body: |
            Update heroicons to latest version.
            - [X] Update icons
            - [X] Update README
            - [ ] Update NuGet package version

            Don't forget to update the [NuGet package version](https://github.com/tmcknight/Blazor.Heroicons/blob/${{ env.branch_name }}/src/Blazor.Heroicons/Blazor.Heroicons.csproj) (if required) before merging this PR.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
